# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee511697166eec09784a224b6020e8418537d5ecf003a4b8f4f987c67f54117e0ef0aa711746972f226699df4907456a60ae1c868261716b3d44791436f07e5

test:
  secret_key_base: f6d509a47f4eecfda7d28c2114a44075e7139fc026fe0321466bf913d14ffe96281b36bca74a4fb8f4aa896569b30baee6e3d7f5852a002b63637499095d2a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
